In [1]:
# üìù Lecture Script: Renaming Columns in a DataFrame
# ===================================================
# This script demonstrates:
# 1. Renaming columns using different methods.
# 2. Best practices and advanced techniques.
# Let‚Äôs dive into renaming column magic! üöÄ

# ------------------------------
# üîπ 1. Import Required Libraries
# ------------------------------
import pandas as pd

# Sample Dataset
data = {
    "Country Name": ["Aruba", "Afghanistan", "Angola", "Albania", "United Arab Emirates"],
    "Country Code": ["ABW", "AFG", "AGO", "ALB", "ARE"],
    "Birth rate": [10.244, 35.253, 45.985, 12.877, 11.044],
    "Internet users": [78.9, 5.9, 19.1, 57.2, 88.0],
    "Income Group": ["High income", "Low income", "Upper middle income", "Upper middle income", "High income"],
}

# Create a DataFrame
stats = pd.DataFrame(data)

# Display Original DataFrame
print("üìä Original DataFrame:")
print(stats)

# ------------------------------
# üîπ 2. Renaming Columns (Method 1: Assign a List)
# ------------------------------
# Assign a new list of column names
stats.columns = ["CountryName", "CountryCode", "BirthRate", "InternetUsers", "IncomeGroup"]

print("\n‚úÖ Renamed Columns using Assignment:")
print(stats.columns)  # Display new column names
print(stats.head())   # Display first few rows to confirm

# ------------------------------
# üîπ 3. Renaming Columns (Method 2: `rename` Function)
# ------------------------------
# Rename columns using a dictionary
stats.rename(
    columns={
        "CountryName": "Country",
        "InternetUsers": "Internet Usage (%)"
    },
    inplace=True
)

print("\n‚úÖ Renamed Columns using `rename` Method:")
print(stats.columns)  # Display new column names
print(stats.head())   # Display first few rows to confirm

# ------------------------------
# üîπ 4. Best Practices
# ------------------------------
# Always ensure column names are:
# 1. Descriptive: Avoid cryptic names like "a", "b", "col_1".
# 2. Consistent: Use a consistent naming style (e.g., camelCase or snake_case).
# 3. Clean: Remove special characters or leading/trailing spaces.

# ------------------------------
# üîπ 5. Advanced Example: Lowercase and Replace Spaces
# ------------------------------
# Lowercase all column names and replace spaces with underscores
stats.columns = stats.columns.str.lower().str.replace(" ", "_")

print("\n‚úÖ Advanced Renaming (lowercase + underscores):")
print(stats.columns)  # Display updated column names
print(stats.head())   # Display first few rows to confirm

# ------------------------------
# üîπ 6. Bonus: Adding Prefixes or Suffixes
# ------------------------------
# Add a prefix to all column names
stats_prefixed = stats.add_prefix("data_")

print("\n‚úÖ Columns with Prefix:")
print(stats_prefixed.columns)

# Add a suffix to all column names
stats_suffixed = stats.add_suffix("_info")

print("\n‚úÖ Columns with Suffix:")
print(stats_suffixed.columns)

üìä Original DataFrame:
           Country Name Country Code  Birth rate  Internet users  \
0                 Aruba          ABW      10.244            78.9
1           Afghanistan          AFG      35.253             5.9
2                Angola          AGO      45.985            19.1
3               Albania          ALB      12.877            57.2
4  United Arab Emirates          ARE      11.044            88.0

          Income Group
0          High income
1           Low income
2  Upper middle income
3  Upper middle income
4          High income

‚úÖ Renamed Columns using Assignment:
Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')
            CountryName CountryCode  BirthRate  InternetUsers  \
0                 Aruba         ABW     10.244           78.9
1           Afghanistan         AFG     35.253            5.9
2                Angola         AGO     45.985           19.1
3               Albania         ALB     12.877           57.2
4  United Arab Emirates         ARE     11.044           88.0

           IncomeGroup
0          High income
1           Low income
2  Upper middle income
3  Upper middle income
4          High income

‚úÖ Renamed Columns using `rename` Method:
Index(['Country', 'CountryCode', 'BirthRate', 'Internet Usage (%)',
       'IncomeGroup'],
      dtype='object')
                Country CountryCode  BirthRate  Internet Usage (%)  \
0                 Aruba         ABW     10.244                78.9
1           Afghanistan         AFG     35.253                 5.9
2                Angola         AGO     45.985                19.1
3               Albania         ALB     12.877                57.2
4  United Arab Emirates         ARE     11.044                88.0

           IncomeGroup
0          High income
1           Low income
2  Upper middle income
3  Upper middle income
4          High income

‚úÖ Advanced Renaming (lowercase + underscores):
Index(['country', 'countrycode', 'birthrate', 'internet_usage_(%)',
       'incomegroup'],
      dtype='object')
                country countrycode  birthrate  internet_usage_(%)  \
0                 Aruba         ABW     10.244                78.9
1           Afghanistan         AFG     35.253                 5.9
2                Angola         AGO     45.985                19.1
3               Albania         ALB     12.877                57.2
4  United Arab Emirates         ARE     11.044                88.0

           incomegroup
0          High income
1           Low income
2  Upper middle income
3  Upper middle income
4          High income

‚úÖ Columns with Prefix:
Index(['data_country', 'data_countrycode', 'data_birthrate',
       'data_internet_usage_(%)', 'data_incomegroup'],
      dtype='object')

‚úÖ Columns with Suffix:
Index(['country_info', 'countrycode_info', 'birthrate_info',
       'internet_usage_(%)_info', 'incomegroup_info'],
      dtype='object')