In [1]:
# Accessing DataFrame Elements: Using .at() and .iat() üß†üìä

# Import necessary libraries
import pandas as pd

# Create a sample DataFrame for demonstration
data = {
    "CountryName": ["Aruba", "Afghanistan", "Angola", "Albania", "Argentina"],
    "CountryCode": ["ABW", "AFG", "AGO", "ALB", "ARG"],
    "BirthRate": [10.244, 35.253, 45.985, 12.877, 17.716],
    "InternetUsers": [78.9, 5.9, 19.1, 57.2, 59.9],
    "IncomeGroup": ["High income", "Low income", "Upper middle income", "Upper middle income", "High income"],
}

# Create the DataFrame
stats = pd.DataFrame(data)

# -----------------------------
# Display the DataFrame
print("Original Dataset:")
print(stats)

# -----------------------------
# 1. Accessing elements with .iat() üîç
# -----------------------------

# Access a specific value using .iat() (row index, column index)
print("\nUsing .iat(): Accessing a value based on integer location:")
value_iat = stats.iat[2, 3]  # Row 2, Column 3
print(f"Value at Row 2, Column 3: {value_iat}")

# -----------------------------
# 2. Accessing elements with .at() üè∑Ô∏è
# -----------------------------

# Access a specific value using .at() (row index, column label)
print("\nUsing .at(): Accessing a value based on label and index:")
value_at = stats.at[2, "InternetUsers"]  # Row 2, Column "InternetUsers"
print(f"Value at Row 2, 'InternetUsers': {value_at}")

# -----------------------------
# 3. Why use .iat() and .at()? üßë‚Äçüè´
# -----------------------------

"""
Key Differences:
- .iat[] is optimized for fast access using integer-based indexing.
- .at[] is used for fast access using label-based indexing.

Performance:
- For large datasets, .iat[] can be faster when working with numeric indices.
- For clear, human-readable code, .at[] is preferred when working with labeled columns.
"""

# -----------------------------
# 4. Adding more rows and using .iat() and .at() ‚öôÔ∏è
# -----------------------------

# Add a new row to the dataset
stats.loc[len(stats)] = ["Brazil", "BRA", 14.5, 65.3, "Upper middle income"]
print("\nUpdated Dataset:")
print(stats)

# Use .iat() to update a specific value (numeric indexing)
print("\nUpdating value using .iat():")
stats.iat[5, 2] = 20.5  # Update BirthRate for Brazil
print(stats)

# Use .at() to update a specific value (label indexing)
print("\nUpdating value using .at():")
stats.at[5, "InternetUsers"] = 75.4  # Update InternetUsers for Brazil
print(stats)

# -----------------------------
# 5. Summary üìù
# -----------------------------

"""
Summary of .iat() and .at():
1Ô∏è‚É£ Use .iat[] for fast, integer-based access and updates.
2Ô∏è‚É£ Use .at[] for intuitive, label-based access and updates.
3Ô∏è‚É£ These methods are more efficient than general .loc[] for single value operations.

Best Practices:
- Use .iat[] for computational tasks requiring speed.
- Use .at[] for clarity when labels are available.
"""

# -----------------------------
# üèÜ Additional Practice: Challenge
# -----------------------------

# TASK: Update the "IncomeGroup" for Afghanistan to "Middle income" using .at().
stats.at[1, "IncomeGroup"] = "Middle income"

print("\nAfter Challenge Update:")
print(stats)

Original Dataset:
   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income
3      Albania         ALB     12.877           57.2  Upper middle income
4    Argentina         ARG     17.716           59.9          High income

Using .iat(): Accessing a value based on integer location:
Value at Row 2, Column 3: 19.1

Using .at(): Accessing a value based on label and index:
Value at Row 2, 'InternetUsers': 19.1

Updated Dataset:
   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income
3      Albania         ALB     12.877           57.2  Upper middle income
4    Argentina         ARG     17.716           59.9          High income
5       Brazil         BRA     14.500           65.3  Upper middle income

Updating value using .iat():
   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income
3      Albania         ALB     12.877           57.2  Upper middle income
4    Argentina         ARG     17.716           59.9          High income
5       Brazil         BRA     20.500           65.3  Upper middle income

Updating value using .at():
   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income
3      Albania         ALB     12.877           57.2  Upper middle income
4    Argentina         ARG     17.716           59.9          High income
5       Brazil         BRA     20.500           75.4  Upper middle income

After Challenge Update:
   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9        Middle income
2       Angola         AGO     45.985           19.1  Upper middle income
3      Albania         ALB     12.877           57.2  Upper middle income
4    Argentina         ARG     17.716           59.9          High income
5       Brazil         BRA     20.500           75.4  Upper middle income